# Generated by Django 5.2.3 on 2025-07-10 12:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactssettings',
            name='email',
            field=ckeditor.fields.RichTextField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactssettings',
            name='phones',
            field=ckeditor.fields.RichTextField(verbose_name='Телефон'),
        ),
    ]
