# Generated by Django 5.2.3 on 2025-07-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactssettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactssettings',
            name='telegram_chat_id',
            field=models.PositiveIntegerField(blank=True, help_text='Ідентифікатор користувача Telegram, якому бот буде відправляти повідомлення.', null=True, verbose_name='telegram_chat_id'),
        ),
    ]
