# Generated by Django 5.2.3 on 2025-06-24 19:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Зображення')),
                ('weight', models.PositiveIntegerField(default=1000, help_text='Чим більша вага, тим далі елемент буде у списку', verbose_name='Вага')),
            ],
            options={
                'verbose_name': 'Зображення категорії',
                'verbose_name_plural': 'Зображення категорії',
            },
        ),
        migrations.CreateModel(
            name='CategoryProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('key', models.CharField(max_length=255, verbose_name='Назва')),
                ('value', models.TextField(verbose_name='Значення')),
                ('weight', models.PositiveIntegerField(default=1000, help_text='Чим більша вага, тим далі елемент буде у списку', verbose_name='Вага')),
            ],
            options={
                'verbose_name': 'Характеристика категорії',
                'verbose_name_plural': 'Характеристики категорії',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег h1 (мета-тег)')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (мета-тег)')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords (мета-тег)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description (мета-тег)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('enabled', models.BooleanField(default=True, help_text='Чи відображати на веб-сайті дану категорію?', verbose_name='Включено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug (URI)')),
                ('price', models.TextField(blank=True, verbose_name='Вартість')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('weight', models.PositiveIntegerField(default=1000, help_text='Чим більша вага, тим далі елемент буде у списку', verbose_name='Вага')),
                ('images', models.ManyToManyField(blank=True, to='catalog.categoryimage', verbose_name='Зображення')),
                ('properties', models.ManyToManyField(blank=True, to='catalog.categoryproperty', verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
    ]
