# Generated by Django 5.2.3 on 2025-06-24 20:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Чи відображати на веб-сайті дану категорію?', verbose_name='Увімкнено'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug (для url)'),
        ),
    ]
