# Generated by Django 5.2.3 on 2025-06-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_description_alter_category_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveIntegerField(default=1000, help_text='Чим більша вага, тим далі елемент буде у списку на сторінці', verbose_name='Вага'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='weight',
            field=models.PositiveIntegerField(default=1000, help_text='Чим більша вага, тим далі елемент буде у списку на сторінці', verbose_name='Вага'),
        ),
        migrations.AlterField(
            model_name='categoryproperty',
            name='weight',
            field=models.PositiveIntegerField(default=1000, help_text='Чим більша вага, тим далі елемент буде у списку на сторінці', verbose_name='Вага'),
        ),
    ]
