# Generated by Django 5.2.3 on 2025-06-30 18:23

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_category_images_remove_category_properties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег h1 (мета-тег)')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (мета-тег)')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords (мета-тег)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description (мета-тег)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('text_1', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст 1')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Сторінка списку категорій',
                'verbose_name_plural': 'Сторінка списку категорій',
            },
        ),
    ]
