# Generated by Django 5.2.3 on 2025-07-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_catalogpage_text_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogpage',
            options={'verbose_name': 'Зміст сторінки списку категорій', 'verbose_name_plural': 'Зміст сторінки списку категорій'},
        ),
    ]
