# Generated by Django 5.2.3 on 2025-07-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_catalogpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(help_text='Зображення буде автоматично приведено до розміру 800*800 пікселей при виводі на сторінці категорії.', upload_to='uploads/%Y/%m/%d/', verbose_name='Зображення'),
        ),
    ]
