# Generated by Django 5.2.3 on 2025-06-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Домашня сторінка', 'verbose_name_plural': 'Домашні сторінки'},
        ),
    ]
