# Generated by Django 5.2.3 on 2025-06-26 17:54

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_created_at_alter_homepage_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Домашня сторінка', 'verbose_name_plural': 'Домашня сторінка'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_1',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст 1'),
        ),
    ]
