# Generated by Django 5.2.3 on 2025-07-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_options_homepage_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Зміст сторінки', 'verbose_name_plural': 'Зміст сторінки'},
        ),
    ]
